set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_TX_CLK
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_TXD0
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_TXD1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_TXD2
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_TXD3
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RXD0
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_MDIO
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_MDC
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RX_CTL
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_TX_CTL
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RX_CLK
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RXD1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RXD2
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RXD3
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_BS2
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to FLASH_DI
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to FLASH_DO
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to FLASH_IO2
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to FLASH_IO3
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to FLASH_CS_N_BS1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to FLASH_CLK
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH1_RESET_N_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO36_SDCMD
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_INT_N
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO38_SDD0
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO39_SDD1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to BOOT_MODE0
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH_LED2_N_R
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to BOOT_MODE1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to PWR_GOOD_R
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to ETH0_RESET_N
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO45_SDIO_EMMC_CLK
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO46_SDD2
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO47_SDD3
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_RESET_N
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D0
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D2
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D3
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D4
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D5
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D6
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_D7
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to RTC_INT_N_R
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_CLK
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_STP
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_DIR
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USB_NXT
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to LED0_N_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to LED1_N_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to LED2_N_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO51_SDA
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO52_SCL
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to USBH_ID_N
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to I2C_INT_N_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to I2C_SDA_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to I2C_SCL_HPS
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO57_CLK
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO58_MOSI
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO59_MISO
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO60_SS0_BS0
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO61_CANRX
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO62_CANTX_CS1
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO63_UART1RX
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO64_UART1TX
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO65_UART0RX
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to HPS_GPIO66_UART0TX_CS0